[application]
name = "rubiks-cube-solver"
default_platform = "web"

[web.app]
title = "Rubik's Cube Solver & Tutorial"
base_path = "."

[web.watcher]
watch_path = ["src"]

[bundle]
identifier = "com.rubiks.cube.solver"
publisher = "Rubik's Cube Solver Team"
